### ISSUE TITLE
Initial comments: Additional topics

### ISSUE THREAD

**Issue by annakrystalli** [jdblischak/ctv-project-workflows#2] opened 2018-10-26 08:25 UTC
Just throwing a few topics out for discussion.

- **dependency management**? (ie should we include things like `packrat`?
- **data management:** data being an important part of project management?
- **documentation:** I know many of the framework packages address workflow documentation, but I'd argue management of functions can be an important part. So things like `roxygen2`, `pkgdown` maybe even `rmarkdown` in it's own right, could be included?
- **archiving**?

The frameworks effectively offer higher level approaches to some of the elements mentioned above. I guess the question is how much of the task view, if any, should address the elements?

**Comment by jdblischak** [comment] 2018-10-26 15:14
@annakrystalli Thanks for the suggestions!

> * dependency management? (ie should we include things like packrat?

I agree this is an important topic, and I had originally included it in my initial draft. But because it is such a big topic in its own right, and @nuest has already started a Task View dedicated to this topic ([Computational Environments and Reproducibility](https://github.com/o2r-project/ctv-computational-environments#readme)), I decided to provide a link to his Task View instead ([commit](https://github.com/jdblischak/r-project-workflows/commit/326b9556328696ba0a22a8f39730624cdd205db4)).

> * data management: data being an important part of project management?

Definitely. Could you suggest some example packages to consider?

> * documentation: I know many of the framework packages address workflow documentation, but I'd argue management of functions can be an important part. So things like roxygen2, pkgdown

For these packages we'll need to make a decision on the scope of the Task View. To me, these are all packages that assist with R package development. My initial reaction is to not include these for the following two reasons:

1. Package development packages (devtools, roxygen2, testthat, pkdown, etc.) are already widely known and well documented (e.g. [r-pkgs book](http://r-pkgs.had.co.nz/)). They are also well-supported in RStudio. So basically, is it worth the effort of expanding the scope of the Task to include them?
1. A data analysis project may or may not include creating an R package. Many of the frameworks in this Task View are essentially trying to provide the structure and tooling to support a typical data analysis project that an R package already has. In essence, I see a fundamental difference between writing code to analyze data, and writing a reusable toolbox of functions (though of course the lines can get blurred).

Also see here for my previous thoughts on package development packages: https://github.com/jdblischak/r-project-workflows/issues/2#issuecomment-422080619

> maybe even rmarkdown in it's own right, could be included?

Literate programming is already covered in the existing Task View [ReproducibleResearch](https://github.com/jdblischak/ctv-project-workflows/blob/master/ProjectWorkflows.md#related-links), which is included in the section [Related Links](https://github.com/jdblischak/ctv-project-workflows/blob/master/ProjectWorkflows.md#related-links).

> archiving?

Definitely. Do you mean packages like [archivist](https://cran.r-project.org/package=archivist)? Maybe this could be combined with data management?

**Comment by jdblischak** [comment] 2018-11-07 20:28
@benmarwick @nuest What are your thoughts on potentially including software development packages or the other suggested categories?

**Comment by jdblischak** [comment] 2020-09-08 10:47
Since our task view was merged with the ReproducibleResearch Task View, the workflow packages are now included with packages on dependency management and archiving, so that worked out well.

**Closed as completed by jdblischak** 2020-09-08 10:47 UTC
